### ISSUE TITLE
Move embeddings from memory to LMDB

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/nerd#46]
In the current implementation, the embeddings are currently loaded in memory, which means having 1.5-2 Gb for each language. 

`need to add more information`
 - [x] input files are the `.vec` which shoudl be references as the wikipedia files 
 - [x] remove the compression, keep the quantisation, the data will be loaded directly in lmdb.
- [x] LMDBs information will be included in the language specific resources
- [x] remove loading of the embeddings/${lang}/ embeddings

**Comment by kermitt2** [comment]
The main step is to reimplement the class Word2VecCompress with a storage in LMDB, without the current bitstream/compression process (LMDB has its own cool bitstream/pagination mechanism).

We could then remove the package it.cnr.isti.hpc entirely I think (move the scorers in the normal embeddings package).

Regarding the two first points in the above list, we could think a bit more how to manage the resources. Maybe we could directly generate the LMDB representations without going through .vec files for the entity embeddings. We could also maybe avoid performing quantization as the main goal of quantization here was to reduce the amount of used memory.

**Comment by kermitt2** [comment]
note to myself: quantization actually impacts similarity score in a slightly positive way

**Comment by kermitt2** [comment]
implemented in branch `lmdb-embeddings`

In order to get the embeddings in LMDB, the documentation has been updated, see http://nerd.readthedocs.io/en/*****/train.html#creating-entity-embeddings

To sum-up:

- no more compression, the embeddings files for word and entities should only be quantized (it will work also with non-quantized files, but the lmdb data size would grow by more than 10GB for each language), it is necessary to re-quantize the .vec file gain because I've updated the format to have something more standard:

```bash
mvn exec:java -Dexec.mainClass=com.scienceminer.nerd.embeddings.Quantizer -Dexec.args="-i /home/lopez/resources/embeddings/wiki.en.vec -o /home/lopez/resources/embeddings/word.embeddings.quantized -hashheader"

mvn exec:java -Dexec.mainClass=com.scienceminer.nerd.embeddings.Quantizer -Dexec.args="-i /home/lopez/resources/embeddings/entity.en.embeddings -o /home/lopez/resources/embeddings/entity.embeddings.quantized -hashheader"
```

- the resulting files should be compressed via gzip and then moved to the data directory file corresponding to each language (the directory with the .csv files). The name of the files must be  `word.embeddings.quantized.gz` and `entity.embeddings.quantized.gz`

- when starting entity-fishing (e.g. launching the test) the embeddings will be loaded into LMDB (it is very fast)

- then the lmdb data files can be updated on amazon S3 for each language and each architecture....

**Comment by kermitt2** [comment]
LMDB database wordEmbeddings and entityEmbeddings are pretty large - total of 11GB binary data for English. Weights are stored as float, however with quantized weights, we could use integer and save some space.

**Comment by lfoppiano** [comment]
Note that for now we have to use shorts and not bytes, as the quantisation needs to be reviewed
