### ISSUE TITLE
500 is returned when fetching some wikidata concepts

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/nerd#60]
Here some examples: 

```
Q31
Q39
Q153
Q678
Q837
Q1007
Q1697
Q2055 -> redirect page to Q2058
Q2149 -> disambiguation page
Q2517 -> no exist
```

**Comment by tantikristanti** [comment]
For these Ids : Q31, Q39, Q153, Q678, Q837, Q1007, Q1041, Q1697, they are ok now.
The problems are for the Ids: Q2055 (Error 400), Q2149 (Error 500), Q2517 (Error 400), Q2528 (Error 400), Q2605 (Error 400).

**Comment by tantikristanti** [comment]
So, for these Ids with the status returned "400 Bad Request":
Q2055 and Q2528 they aren't exist anymore due to the direction page.
Meanwhile, Q2517 and Q2605, they aren't exist.

Nerd has anticipated this situation by giving a message for users.

<img width="1358" alt="screen shot 2018-02-08 at 11 52 41" src="https://user-images.githubusercontent.com/28044697/35969269-989bc260-0cc6-11e8-81a7-5e3c225beef1.png">

**Comment by tantikristanti** [comment]
For the case of Id: Q2149, there are some bugs regarding the casting from Page type to Article type. The problem arrises because as default, Page type will be casted into Article by default without any examination whether Page type can be casted or not.

**Comment by tantikristanti** [comment]
This issue is closed with the reason that all possibilities of bugs have been solved.
